# Generated by Django 3.1.4 on 2023-05-17 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20230510_2242'),
    ]

    operations = [
    ]
